from datetime import datetime, timedelta
from dateutil.tz import tzlocal

def make_job_sample():
  sample_job_runs = {
      "job2": [
          {
              'Id': 'jr_b201',
              'Attempt': 0,
              'TriggerName': 'tg2',
              'JobName': 'job2',
              'StartedOn': datetime(2025, 7, 1, 10, 0, 0, 100000, tzinfo=tzlocal()),
              'LastModifiedOn': datetime(2025, 7, 1, 10, 0, 30, 500000, tzinfo=tzlocal()),
              'CompletedOn': datetime(2025, 7, 1, 10, 0, 30, 500000, tzinfo=tzlocal()),
              'JobRunState': 'FAILED',
              'Arguments': {},
              'PredecessorRuns': [],
              'AllocatedCapacity': 0,
              'ExecutionTime': 30,
              'Timeout': 2880,
              'MaxCapacity': 0.125,
              'LogGroupName': '/aws-glue/python-jobs',
              'GlueVersion': '3.0',
              'ExecutionClass': 'STANDARD',
          },
          {
              'Id': 'jr_b202',
              'Attempt': 0,
              'TriggerName': 'tg2',
              'JobName': 'job2',
              'StartedOn': datetime(2025, 7, 1, 9, 50, 0, 300000, tzinfo=tzlocal()),
              'LastModifiedOn': datetime(2025, 7, 1, 9, 50, 20, 900000, tzinfo=tzlocal()),
              'CompletedOn': datetime(2025, 7, 1, 9, 50, 20, 900000, tzinfo=tzlocal()),
              'JobRunState': 'SUCCEEDED',
              'Arguments': {},
              'PredecessorRuns': [],
              'AllocatedCapacity': 0,
              'ExecutionTime': 20,
              'Timeout': 2880,
              'MaxCapacity': 0.125,
              'LogGroupName': '/aws-glue/python-jobs',
              'GlueVersion': '3.0',
              'ExecutionClass': 'STANDARD',
          },
          {
              'Id': 'jr_b203',
              'Attempt': 0,
              'TriggerName': 'tg2',
              'JobName': 'job2',
              'StartedOn': datetime(2025, 7, 1, 9, 40, 0, 700000, tzinfo=tzlocal()),
              'LastModifiedOn': datetime(2025, 7, 1, 9, 45, 0, 700000, tzinfo=tzlocal()),
              'CompletedOn': datetime(2025, 7, 1, 9, 45, 0, 700000, tzinfo=tzlocal()),
              'JobRunState': 'TIMEOUT',
              'Arguments': {},
              'PredecessorRuns': [],
              'AllocatedCapacity': 0,
              'ExecutionTime': 300,
              'Timeout': 2880,
              'MaxCapacity': 0.125,
              'LogGroupName': '/aws-glue/python-jobs',
              'GlueVersion': '3.0',
              'ExecutionClass': 'STANDARD',
          },
      ],
      "job3": [
          {
              'Id': 'jr_c301',
              'Attempt': 0,
              'TriggerName': 'tg3',
              'JobName': 'job3',
              'StartedOn': datetime(2025, 7, 1, 10, 10, 0, 0, tzinfo=tzlocal()),
              'LastModifiedOn': datetime(2025, 7, 1, 10, 10, 30, 0, tzinfo=tzlocal()),
              'CompletedOn': datetime(2025, 7, 1, 10, 10, 30, 0, tzinfo=tzlocal()),
              'JobRunState': 'RUNNING',
              'Arguments': {},
              'PredecessorRuns': [],
              'AllocatedCapacity': 0,
              'ExecutionTime': 0,
              'Timeout': 2880,
              'MaxCapacity': 0.125,
              'LogGroupName': '/aws-glue/python-jobs',
              'GlueVersion': '3.0',
              'ExecutionClass': 'STANDARD',
          },
          {
              'Id': 'jr_c302',
              'Attempt': 0,
              'TriggerName': 'tg3',
              'JobName': 'job3',
              'StartedOn': datetime(2025, 7, 1, 9, 55, 0, 0, tzinfo=tzlocal()),
              'LastModifiedOn': datetime(2025, 7, 1, 9, 55, 25, 0, tzinfo=tzlocal()),
              'CompletedOn': datetime(2025, 7, 1, 9, 55, 25, 0, tzinfo=tzlocal()),
              'JobRunState': 'SUCCEEDED',
              'Arguments': {},
              'PredecessorRuns': [],
              'AllocatedCapacity': 0,
              'ExecutionTime': 25,
              'Timeout': 2880,
              'MaxCapacity': 0.125,
              'LogGroupName': '/aws-glue/python-jobs',
              'GlueVersion': '3.0',
              'ExecutionClass': 'STANDARD',
          },
          {
              'Id': 'jr_c303',
              'Attempt': 0,
              'TriggerName': 'tg3',
              'JobName': 'job3',
              'StartedOn': datetime(2025, 7, 1, 9, 50, 0, 0, tzinfo=tzlocal()),
              'LastModifiedOn': datetime(2025, 7, 1, 9, 50, 40, 0, tzinfo=tzlocal()),
              'CompletedOn': datetime(2025, 7, 1, 9, 50, 40, 0, tzinfo=tzlocal()),
              'JobRunState': 'FAILED',
              'Arguments': {},
              'PredecessorRuns': [],
              'AllocatedCapacity': 0,
              'ExecutionTime': 40,
              'Timeout': 2880,
              'MaxCapacity': 0.125,
              'LogGroupName': '/aws-glue/python-jobs',
              'GlueVersion': '3.0',
              'ExecutionClass': 'STANDARD',
          },
      ]
  }
  return sample_job_runs
