name: Deploy Streamlit App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          echo "No tests defined yet"

      - name: Build Docker Image
        run: |
          docker build -t aws-glue-monitoring-app:latest .

      # Deploy step: 예시 - EC2 서버에 ssh로 배포 (Railway/ECS 등도 가능)
      - name: Deploy to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.SERVER_USER }}/aws-glue-monitoring-app"

      - name: Remote Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd glue-monitor
            docker stop aws-glue-monitoring-app || true
            docker rm aws-glue-monitoring-app || true
            docker build -t aws-glue-monitoring-app .
            docker run -d -p 8501:8501 --name aws-glue-monitoring-app
